Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Morris_Isaac_Homework7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Morris_Isaac_Homework7.Components
{
    //NavigationMenu View Component to display filtered results by Book Category to user
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBooklistRepository repository;

        public NavigationMenuViewComponent (IBooklistRepository r)
        {
            repository = r;
        }

        public IViewComponentResult Invoke()
        {
            //Select all distinct categories from books in database and display in Navigation Menu
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x)
                );
        }
    }
}

Views/Shared/BookSummary.cshtml
@model Book

<div class="card card-light m-1 p-1">
    <div class="bg-light p-2">
        <div>
            <h4>Book Title: @Model.Title</h4>
            <p>Author: @Model.Author</p>
            <p>Publisher: @Model.Publisher</p>
            <p>ISBN: @Model.ISBN</p>
            <p>Classification: @Model.Classification</p>
            <p>Category: @Model.Category</p>
            <p>Price: @Model.Price</p>
        </div>
    </div>

    <form id="@Model.BookId" asp-page-handler="/Purchase" method="post">
        <input type="hidden" asp-for="BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Title
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Overall Layout page to be shared between all pages-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<!-- Main default layout for all pages within Bookstore site-->
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">HILTON'S BOOKS</span>
    </div>
    <div class="row m-1 p-1">
        <div class="col-9">
            @RenderBody()
        </div>
        <div class="col-3 p-5">
            <h3>Category</h3>
            <vc:navigation-menu />
        </div>
    </div>
</body>
</html>