Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Morris_Isaac_Homework7.Infrastructure;
using Morris_Isaac_Homework7.Models;

namespace Morris_Isaac_Homework7.Pages
{
    public class PurchaseModel : PageModel
    {
        private IBooklistRepository repository;
        public PurchaseModel(IBooklistRepository repo, Cart CartService)
        {
            repository = repo;
            Cart = CartService;
        }
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(long BookId, string returnUrl)
        {
            Book book = repository.Books.FirstOrDefault(p => p.BookId == BookId);

            Cart.AddItem(book, 1);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long BookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
                cl.Book.BookId == BookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Purchase.cshtml
@page
@model Morris_Isaac_Homework7.Pages.PurchaseModel
@{
}
<h2>Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Project</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-left">@line.Book.Title</td>
            <td class="text-center">@line.Quantity</td>
            <td class="text-right">@line.Book.Price</td>
            <td class="text-right">@((line.Quantity*line.Book.Price).ToString("c"))</td>
            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="BookId" value="@line.Book.BookId" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                </form>
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td class="text-right" colspan="3">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalSum().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>